export const metrics = [
  {
    label: "Circulation (USD, 180d)",
    metric: "circulation_usd_180d",
    lineStyle: { color: "#4B88A2", width: 2, type: "solid" },
    areaStyle: {
      color: "rgba(75, 136, 162, 0.4)",
      opacity: 0.4,
      shadowBlur: 10,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
    },
  },
  {
    label: "Community Messages Count (Total)",
    metric: "community_messages_count_total",
    lineStyle: { color: "#6A0572", width: 2, type: "dotted" },
    areaStyle: {
      color: "rgba(106, 5, 114, 0.3)",
      opacity: 0.3,
      shadowBlur: 8,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
    },
  },
  {
    label: "Median Fees (USD)",
    metric: "median_fees_usd",
    lineStyle: { color: "#A23B72", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(162, 59, 114, 0.5)",
      opacity: 0.5,
      shadowBlur: 12,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
    },
  },
  {
    label: "Transaction Volume (USD)",
    metric: "transaction_volume_usd",
    lineStyle: { color: "#FFAA4C", width: 2, type: "solid" },
    areaStyle: {
      color: "rgba(255, 170, 76, 0.3)",
      opacity: 0.3,
      shadowBlur: 8,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
    },
  },
  {
    label: "MVRV (USD, 30d)",
    metric: "mvrv_usd_30d",
    lineStyle: { color: "#20BF55", width: 2, type: "dashed" },
    areaStyle: {
      color: "rgba(32, 191, 85, 0.4)",
      opacity: 0.4,
      shadowBlur: 10,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
    },
  },
  {
    label: "Network Circulation (USD, 1d)",
    metric: "network_circulation_usd_1d",
    lineStyle: { color: "#3E92CC", width: 1.5, type: "solid" },
    areaStyle: {
      color: "rgba(62, 146, 204, 0.4)",
      opacity: 0.4,
      shadowBlur: 12,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
    },
  },
  {
    label: "Network Growth",
    metric: "network_growth",
    lineStyle: { color: "#F45D01", width: 2, type: "solid" },
    areaStyle: {
      color: "rgba(244, 93, 1, 0.3)",
      opacity: 0.3,
      shadowBlur: 10,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
    },
  },
  {
    label: "Network Profit/Loss",
    metric: "network_profit_loss",
    lineStyle: { color: "#7A4579", width: 2, type: "dotted" },
    areaStyle: {
      color: "rgba(122, 69, 121, 0.4)",
      opacity: 0.4,
      shadowBlur: 8,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
    },
  },
  {
    label: "Sentiment Balance (Total)",
    metric: "sentiment_balance_total",
    lineStyle: { color: "#3D348B", width: 2, type: "solid" },
    areaStyle: {
      color: "rgba(61, 52, 139, 0.4)",
      opacity: 0.4,
      shadowBlur: 10,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
    },
  },
  {
    label: "Sentiment Negative (Total)",
    metric: "sentiment_negative_total",
    lineStyle: { color: "#E63946", width: 1.5, type: "solid" },
    areaStyle: {
      color: "rgba(230, 57, 70, 0.3)",
      opacity: 0.3,
      shadowBlur: 10,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
    },
  },
  {
    label: "Sentiment Positive (Total)",
    metric: "sentiment_positive_total",
    lineStyle: { color: "#52B788", width: 2, type: "dashed" },
    areaStyle: {
      color: "rgba(82, 183, 136, 0.4)",
      opacity: 0.4,
      shadowBlur: 8,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
    },
  },
  {
    label: "Sentiment Volume Consumed (Total)",
    metric: "sentiment_volume_consumed_total",
    lineStyle: { color: "#F1C40F", width: 2, type: "dotted" },
    areaStyle: {
      color: "rgba(241, 196, 15, 0.4)",
      opacity: 0.4,
      shadowBlur: 10,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
    },
  },
  {
    label: "Sentiment Weighted (Total)",
    metric: "sentiment_weighted_total",
    lineStyle: { color: "#2C3E50", width: 1.5, type: "solid" },
    areaStyle: {
      color: "rgba(44, 62, 80, 0.4)",
      opacity: 0.4,
      shadowBlur: 12,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
    },
  },
  {
    label: "Social Dominance AI (Total)",
    metric: "social_dominance_ai_total",
    lineStyle: { color: "#F79D84", width: 2, type: "dashed" },
    areaStyle: {
      color: "rgba(247, 157, 132, 0.3)",
      opacity: 0.3,
      shadowBlur: 8,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
    },
  },
  {
    label: "Social Dominance (Total)",
    metric: "social_dominance_total",
    lineStyle: { color: "#8E44AD", width: 2, type: "solid" },
    areaStyle: {
      color: "rgba(142, 68, 173, 0.4)",
      opacity: 0.4,
      shadowBlur: 12,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
    },
  },
  // Add more metrics similarly, if needed...
];
