export const santimentMetrics = [
  {
    label: "Developer Activity",
    metric: "dev_activity",
    lineStyle: { color: "#FF6347", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(255, 99, 71, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "GitHub Activity",
    metric: "github_activity",
    lineStyle: { color: "#FF7F50", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(255, 127, 80, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "Active Addresses (30 Days)",
    metric: "active_addresses_30d",
    lineStyle: { color: "#FFD700", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(255, 215, 0, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "Transaction Volume (USD)",
    metric: "transaction_volume_usd",
    lineStyle: { color: "#ADFF2F", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(173, 255, 47, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "MVRV (USD, 30 Days)",
    metric: "mvrv_usd_30d",
    lineStyle: { color: "#32CD32", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(50, 205, 50, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "Weighted Sentiment Total",
    metric: "sentiment_weighted_total",
    lineStyle: { color: "#00FA9A", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(0, 250, 154, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "Social Volume Total",
    metric: "social_volume_total",
    lineStyle: { color: "#48D1CC", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(72, 209, 204, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },

  {
    label: "Circulation (USD, 180 Days)",
    metric: "circulation_usd_180d",
    lineStyle: { color: "#4169E1", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(65, 105, 225, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },

  {
    label: "Developer Activity Contributors Count",
    metric: "dev_activity_contributors_count",
    lineStyle: { color: "#8A2BE2", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(138, 43, 226, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },

  {
    label: "GitHub Activity Contributors Count",
    metric: "github_activity_contributors_count",
    lineStyle: { color: "#FF1493", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(255, 20, 147, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "Sentiment Balance Total",
    metric: "sentiment_balance_total",
    lineStyle: { color: "#FF4500", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(255, 69, 0, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },

  {
    label: "Daily Active Addresses",
    metric: "daily_active_addresses",
    lineStyle: { color: "#B22222", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(178, 34, 34, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "Twitter Followers",
    metric: "twitter_followers",
    lineStyle: { color: "#DC143C", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(220, 20, 60, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "Positive Sentiment Total",
    metric: "sentiment_positive_total",
    lineStyle: { color: "#FF69B4", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(255, 105, 180, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
  {
    label: "Social Dominance (AI Total)",
    metric: "social_dominance_ai_total",
    lineStyle: { color: "#00BFFF", width: 1, type: "solid" },
    areaStyle: {
      color: "rgba(0, 191, 255, 0.4)",
      opacity: 0.4,
      shadowBlur: 15,
      shadowOffsetX: 10,
      shadowOffsetY: 10,
    },
  },
];
